config/routes.rb
Rails.application.routes.draw do
  get 'dash_boards/index'
  devise_for :users, controllers: {
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  
  root 'home#index'

  resources :dash_boards, only: [:index]

  # 追加するルート
  namespace :users do
    resources :articles, path: '/articles'
  end
  

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_one_attached :image

  validates :title, presence: true, length: { maximum: 10 }
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
       :recoverable, :rememberable, :validatable, :confirmable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    puts "Configuring permitted parameters for Devise..."
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/dash_boards_controller.rb
class DashBoardsController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users/articles_controller.rb
class Users::ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!


  # GET /articles
  def index
    @articles = Article.all
  end

  # GET /articles/1
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to users_articles_path, notice: '新規作成に成功しました。'
    else
      puts @article.errors.full_messages # エラーメッセージを出力
      render :new
    end
  end


  # PATCH/PUT /articles/1
  def update
    if @article.update(article_params)
      redirect_to users_articles_url, notice: '記事を更新しました。'
    else
      puts @article.errors.full_messages # エラーメッセージを出力
      render :edit
    end
  end
  

  # DELETE /articles/1
  def destroy
    @article.destroy
    redirect_to users_articles_url, notice: '記事を削除しました。'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :content, :image)
    end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  protected

  def after_resetting_password_path_for(resource)
    dash_boards_index_path
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_update_path_for(resource)
    dash_boards_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dash_boards_helper.rb
module DashBoardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users/articles_helper.rb
module Users::ArticlesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dash_boards/index.html.erb
<h1 class="text-center mb-4">Dash Boards</h1>


  <div class="row justify-content-center">
    <div class="col-md-6">
      <% if user_signed_in? %>
        <p class="lead text-center"><%= current_user.name %></p>
        <div class="d-grid gap-2">
          <%= link_to "記事一覧", users_articles_path, class: "btn btn-primary btn-block" %>
          <%= link_to "編集", edit_user_registration_path, class: "btn btn-primary btn-block" %>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn btn-warning btn-block" %>
        </div>
      <% end %>
    </div>
  </div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<%# もしユーザーがログインしていなかったら %>
<% if !user_signed_in? %>
  <%= link_to "新規登録", new_user_registration_path %>
  <%= link_to "ログイン", new_user_session_path %>
<% end %>

<%# ログインしていたらログアウトボタンを表示する %>
<% if user_signed_in? %>
  <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
<% end %>

<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Practice</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <% if flash[:notice] %>
      <p><%= flash[:notice] %></p>
    <% end %>
    <% if flash[:alert] %>
        <p><%= flash[:alert] %></p>
    <% end %>

    
    
    <%= yield %>
  </body>
</html>

app/views/users/articles/edit.html.erb
<div class="container">
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2 class="text-danger">
        更新に失敗しました、以下のエラーを修正してください。
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="text-center">
  <h1>記事の編集</h1>
  </div>

  <%= form_with(model: @article, url: users_article_path(@article), local: true, html: { method: :patch, multipart: true }) do |form| %>
    <div class="mb-3">
      <%= form.label :title, "タイトル" %>
      <%= form.text_field :title, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :content, "内容" %>
      <%= form.text_area :content, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :image, "画像" %>
      <div class="input-group">
        <%= form.file_field :image, class: "form-control", style: "display: none;", id: "imageFile", onchange: "updateFileName(this)" %>
        <label for="imageFile" class="btn btn-secondary">ファイルを選択</label>
      </div>
      <span id="fileName">選択されていません</span>
    </div>

    <div class="text-center">
      <%= form.submit "更新", class: "btn btn-primary" %>
    </div>
  <% end %>

  <%= link_to "記事一覧へ戻る", users_articles_path %>

  <script>
  function updateFileName(input) {
    if (input.files && input.files[0]) {
      document.getElementById('fileName').innerText = input.files[0].name;
    } else {
      document.getElementById('fileName').innerText = "選択されていません";
    }
  }
  </script>
</div>

app/views/users/articles/index.html.erb
<div class="container">
  <div class="text-center">
    <h1>記事一覧</h1>
    <%= link_to "記事新規作成", new_users_article_path, class: "btn btn-primary" %>
  </div>

  <table class="table">
    <thead>
      <tr>
        <th>詳細表示</th>
        <th>タイトル</th>
        <th>内容</th>
        <th>画像</th>
        <th>編集・削除</th>
      </tr>
    </thead>
    <tbody>
      <% @articles.each do |article| %>
        <tr>
          <td><%= link_to "詳細", users_article_path(article), class: "btn btn-primary" %></td>
          <td><%= article.title %></td>
          <td><%= article.content %></td>
          <td><%= image_tag article.image.variant(resize_to_limit: [300, 300]) if article.image.attached? %></td>
          <td>
            <%= link_to "編集", edit_users_article_path(article), class: "btn btn-primary" %>
            <%= link_to "削除", users_article_path(article), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-danger" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/articles/new.html.erb
<div class="container">
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2 class="text-danger">
        新規作成に失敗しました、以下のエラーを修正してください。
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="text-center">
    <h1>記事の新規作成</h1>
  </div>



  <%= form_with(model: @article, url: users_articles_path, local: true, html: { multipart: true }) do |form| %>
    <div class="mb-3">
      <%= form.label :title, "タイトル" %>
      <%= form.text_field :title, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :content, "内容" %>
      <%= form.text_area :content, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :image, "画像" %>
      <div class="input-group">
        <%= form.file_field :image, class: "form-control", style: "display: none;", id: "imageFile", onchange: "updateFileName(this)" %>
        <label for="imageFile" class="btn btn-secondary">ファイルを選択</label>
      </div>
      <span id="fileName">選択されていません</span>
    </div>

    <div class="text-center">
      <%= form.submit "新規作成", class: "btn btn-primary" %>
    </div>
    
  <% end %>

  <script>
  function updateFileName(input) {
    if (input.files && input.files[0]) {
      document.getElementById('fileName').innerText = input.files[0].name;
    } else {
      document.getElementById('fileName').innerText = "選択されていません";
    }
  }
  </script>

  <%= link_to "戻る", users_articles_path %>
</div>

app/views/users/articles/show.html.erb
<h1 class="text-center">記事詳細</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th class="text-center">タイトル</th>
      <th class="text-center">内容</th>
      <th class="text-center">画像</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td class="text-center"><%= @article.title %></td>
      <td class="text-center"><%= @article.content %></td>
      <td class="text-center"><%= image_tag @article.image.variant(resize_to_limit: [500, 500]) if @article.image.attached? %></td>
    </tr>
  </tbody>
</table>

<div class="text-center">
  <%= link_to "編集", edit_users_article_path(@article), class: "btn btn-success" %>
  <%= link_to "削除", users_article_path(@article), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-danger" %>
</div>

<div class="text-center mt-3">
  <%= link_to "記事一覧に戻る", users_articles_path, class: "btn btn-primary" %>
</div>

app/views/users/show.html.erb
<%= @user.name %>